### ISSUE TITLE
tikz2ipe possible ?

### ISSUE THREAD

**Issue by fbob** [QBobWatson/ipe2tikz#1]
What an awesome project  :)

I was looking for this kind of tool for a very very very long time and your made it.
Many many thanks for sharing this wonderful ipelet !

Juts a newbie question, will it be possible to have a tikz import feature aka tikz2ipe ?

Any way, thank you very much and long life to ipe2tikz
Cheers

**Comment by QBobWatson** [comment]
Thanks for the encouragement!  There's some more functionality suggested by Otfried that I'm working on now and should appear soon.

I did briefly consider making a converter the other way, but quickly realized that there are many real difficulties.  A direct converter (something that takes raw TikZ code and produces an Ipe image) would be essentially impossible, because TikZ uses TeX as a programming language to programmatically create pictures in a very flexible way.  One would end up re-implementing all of TeX to figure out what TikZ was actually doing.  This leaves the following options:
1. Convert PDF --> Ipe.  I'm not sure there's a program that does this conversion directly, but it should be possible to go PDF --> SVG --> Ipe.  Of course, one loses all information about style sheets, arrow tips, etc.
2. Make an Ipe backend device for PGF.  This would probably be easier than (1), but the results would not be so different I expect.  Also, like I said, I believe (1) is already implemented.

Anyway, neither option seems worth pursuing to me.  The formats are really not interchangeable, since TikZ is strictly more complicated than Ipe.

Cheers,
Joe

**Comment by fbob** [comment]
Hi Joe, 

Thank you very much for your feedback which indeed clearly reveal the difficulties of a tikz import in Ipe. 
I read on the mailing list the features suggested by Otfried, very exciting functionality :) 

I really enjoy your ipelet, congratulations for your awesome work. 
THANK YOU :) 
François
